version: '3.3'

services:
    
  # ======================================
  # -- frontend
  # ======================================
  frontend:
    build:
      context: .
      dockerfile: ./_local/Dockerfile
    volumes:
      - ./:/frontend/
    ports:
      - 8100:8100
